version: '2'
services:
    app-postgresql:
        image: postgres:10.1
        volumes:
            - ./postgres/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=fred
        ports:
            - 5432:5432
